services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=backend_stuff
      - POSTGRES_PASSWORD=robinrobin
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.4.1-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://backend_stuff:robinrobin@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]

volumes:
  postgres:
