name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::533075172220:role/simplebank-deployment
        aws-region: ap-south-1
        audience: sts.amazonaws.com

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 

    - name: Checkout private secrets repo
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.SIMPLEBANK_ENV_REPO }}
        token: ${{ secrets.SIMPLEBANK_GITHUB_TOKEN }}
        path: ${{ secrets.SIMPLEBANK_ENV_REPO_NAME }}

    - name: Set environment variables for productions
      run: |
        cp ${{ secrets.SIMPLEBANK_ENV_REPO_NAME }}/app.env app.env

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
        docker push -a $REGISTRY/$REPOSITORY

  deploy:
    name: Deploy to production
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout private secrets repo
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.SIMPLEBANK_ENV_REPO }}
        token: ${{ secrets.SIMPLEBANK_GITHUB_TOKEN }}
        path: ${{ secrets.SIMPLEBANK_ENV_REPO_NAME }}

    - name: Copy deployment file via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        source: "${{ secrets.SIMPLEBANK_ENV_REPO_NAME }}/deploy.sh"
        target: ~/simplebank

    - name: Run deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd simplebank/${{ secrets.SIMPLEBANK_ENV_REPO_NAME }}
          chmod +x deploy.sh
          ./deploy.sh >> ~/simplebank/deploy.log 2>&1
          rm deploy.sh
          cd ../ && rm -rf ${{ secrets.SIMPLEBANK_ENV_REPO_NAME }}
